spring:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/<db_name>
    username: <your_db_username>
    password: <your_db_password>
    pool-size: 30

  security:
    user:
      name: test
      password: test
      roles: superuser